apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.14.1.9
#    - 10.14.1.9-10.14.1.9 # IP range reserved for the Load balancer